# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Deno

on:
  workflow_dispatch:
  
#   schedule:
#     - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: run update-data
        run: deno run --allow-net --allow-read --allow-write --allow-env update-data.ts
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
  
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update data
          commit_author: Author <actions@github.com>
